image: gitpod/workspace-mysql

tasks:
    - before: sdk install java 17.0.4.1-tem < /dev/null
    - name: API Build
      command: cd ecommerce-api && mvn spring-boot:run
    - name: UI Build
      command: cd ecommerce-ui && npm install && npm start
      openMode: split-right