DROP TABLE IF EXISTS customers;
CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    `role` VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

